site_name: Analizador de texto
nav:
  - Home: index.md
  - Install: installation.md
  - Usage: usage.md
  - Scripts: scripts.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
